name: m4gp
channels:
    - conda-forge
dependencies:
    - python=3.*
    - eigen=3.3.7
    - boost=1.74.0
    - scikit-learn
    - pandas=1.1.*
    - pip
    - pip:
        - DistanceClassifier
        - skrebate
    # - setuptools=45.*
    # - wheel=0.35.*
    # - pip=20.*
    # - pip:
